### ISSUE TITLE
Option to preview in Yaml

### ISSUE THREAD

**Issue by ant31** [heptio/vscode-jsonnet#3]
Most of Kubernetes resources are 'hand-written' in Yaml. 
An preview in Yaml may help users to get a quicker diff with what they are used to see.

**Comment by hausdorff** [comment]
I would have done that, except my understanding is that the `jsonnet` command line does not support generating YAML yet. (Or, technically, I guess that it does, since YAML is a superset of JSON, but I think you know what I mean. :) )

If you happen to know differently, I'm happy to add that to the extension. If not, I think it will have to wait until I can convince Dave to let me to add this capability to the tool.

**Comment by ant31** [comment]
Yes, I think you can work around very easily inside the tool. 
https://github.com/heptio/vscode-jsonnet/blob/master/src/extension.ts#L186
you can have an option to either pretty print in JSON or in YAML (with a yaml parser in typescript)

I'll try to submit a PR.

**Comment by hausdorff** [comment]
To follow up, I changed a couple things in my follow-up commit. The big thing is that I changed the option from `jsonnet.outputStyle` -> `jsonnet.outputFormat`. You can see more details in the commit message: https://github.com/heptio/vscode-jsonnet/commit/fb16b446bfbaa044f297c40d2aaf3975ed50ab9a

Let me know if you disagree with something in this commit.
